app/models/user.py
import jwt
from flask import current_app
from app.extensions import db, login
from time import time
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), nullable=False, unique=True)
    password_hash = db.Column(db.String(128))
    alias = db.Column(db.String(100))
    admin = db.Column(db.Boolean, default=False)

    #Relations
    tvshow_picks = db.relationship('TVShowPick', backref='picker', lazy='dynamic')
    movie_picks = db.relationship('MoviePick', backref='picker', lazy='dynamic')

    def __repr__(self) -> str:
        return f'User: {self.email}'

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def set_admin(self, admin):
        self.admin = bool(admin)

    def get_reset_password_token(self, expires_in=600):
        return jwt.encode({'reset_password': self.id, 'exp': time() + expires_in}, current_app.config["SECRET_KEY"], algorithm='HS256')

    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(token, current_app.config["SECRET_KEY"], algorithms=['HS256'])['reset_password']
        except:
            return
        return User.query.get(id)
    
@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/models/users.py
import jwt
from flask import current_app
from app.extensions import db, login
from time import time
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin, AnonymousUserMixin

def default_alias(context):
    return context.get_current_parameters()['email']

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(120), nullable=False, unique=True)
    password_hash = db.Column(db.String(128))
    alias = db.Column(db.String(100), default=default_alias)
    last_seen = db.Column(db.DateTime(), default=None)
    movie_storage_usage = db.Column(db.BigInteger, default=0)
    show_storage_usage = db.Column(db.BigInteger, default=0)

    role_id = db.Column(db.Integer, db.ForeignKey('role.id'))
    picks = db.relationship('Pick', back_populates='user', cascade='all, delete')

    def __repr__(self) -> str:
        return f'User: {self.email}'

    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            self.role = Role.query.filter_by(default=True).first()

    def ping(self):
        self.last_seen = datetime.utcnow()
        db.session.add(self)
        db.session.commit()

    def can(self, perm):
        return self.role is not None and self.role.has_permission(perm)

    def is_administrator(self):
        return self.can(Permission.ADMIN)

    def is_super_user(self):
        return self.can(Permission.SUPERUSER)

    def is_system_user(self):
        return self.role.name == "System User"

    def set_role(self, role_name):
        role = Role.query.filter_by(name=role_name).first()
        self.role = role
        db.session.add(self)
        db.session.commit()

    def set_alias(self, alias):
        self.alias = alias
        db.session.add(self)
        db.session.commit()

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def get_reset_password_token(self, expires_in=600):
        return jwt.encode({'reset_password': self.id, 'exp': time() + expires_in}, current_app.config["SECRET_KEY"], algorithm='HS256')

    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(token, current_app.config["SECRET_KEY"], algorithms=['HS256'])['reset_password']
        except:
            return
        return User.query.get(id)

    @staticmethod
    def admins_count():
        num_admins = 0
        for user in User.query.all():
            if (user.is_administrator()):
                num_admins += 1
        return num_admins

    @staticmethod
    def insert_system_users():
        users = {
            'Permanent',
        }
        for u in users:
            user = User.query.filter_by(email=u).first()
            if user is None:
                user = User(email=u)
                db.session.add(user)
                db.session.commit()
                user.set_role('System User')

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class AnonymousUser(AnonymousUserMixin):
    def can(self, permissions):
        return False
    def is_administrator(self):
        return False
    def is_super_user(self):
        return False

login.anonymous_user = AnonymousUser

class Role(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __init__(self, **kwargs):
        super(Role, self).__init__(**kwargs)
        if self.permissions is None:
            self.permissions = 0

    def add_permission(self, perm):
        if not self.has_permission(perm):
            self.permissions += perm
    def remove_permission(self, perm):
        if self.has_permission(perm):
            self.permissions -= perm
    def reset_permissions(self):
        self.permissions = 0
    def has_permission(self, perm):
        return self.permissions & perm == perm

    @staticmethod
    def insert_roles():
        roles = {
            'User': [],
            'System User': [],
            'Power User': [Permission.SUPERUSER],
            'Administrator': [Permission.ADMIN, Permission.SUPERUSER],
        }
        default_role = 'User'
        for r in roles:
            role = Role.query.filter_by(name=r).first()
            if role is None:
                role = Role(name=r)
            role.reset_permissions()
            for perm in roles[r]:
                role.add_permission(perm)
            role.default = (role.name == default_role)
            db.session.add(role)
        db.session.commit()

class Permission:
    #Use binary
    ADMIN = 1
    SUPERUSER = 2

app/settings/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, BooleanField, SubmitField, validators, ValidationError, SelectField, DateTimeLocalField
from wtforms.validators import DataRequired
from app.models import User, Role


class EditUserForm(FlaskForm):
    email = StringField('Email Address')
    alias = StringField('Alias', validators=[DataRequired()])
    #Need to make this better to go according to Role class
    role = SelectField('Role', choices=["User", "Power User", "Administrator"])
    submit = SubmitField('Save')

class AddUserForm(FlaskForm):
    email = StringField('Email Address', validators=[DataRequired()])
    alias = StringField('Alias', validators=[DataRequired()])
    role = SelectField('Role', choices=["User", "Power User", "Administrator"])
    submit = SubmitField('Save')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('An account with that email address is already present.')
        
class EditAppSettings(FlaskForm):
    expiry_time_number = IntegerField("After how much time should an abandoned media be marked expired", validators=[validators.NumberRange(min=0)])
    expiry_time_unit = SelectField('Unit', choices=["minutes","hours","days","weeks","months"])
    next_delete = DateTimeLocalField('When should the next check for deletion of expired media be', format='%Y-%m-%dT%H:%M')
    deletion_time_number = IntegerField('Reoccurs every', validators=[validators.NumberRange(min=0)])
    deletion_time_unit = SelectField('Unit', choices=["hours","days","weeks","months",])
    app_name = StringField('Application Name')
    radarr_host = StringField()
    radarr_port = IntegerField(validators=[validators.Optional()])
    radarr_api_key = StringField()
    sonarr_host = StringField()
    sonarr_port = IntegerField(validators=[validators.Optional()])
    sonarr_api_key = StringField()
    ombi_host = StringField()
    ombi_port = IntegerField(validators=[validators.Optional()])
    ombi_api_key = StringField()
    safe_mode = BooleanField('Safe Mode. Allows to delete objects only from the SeenIt database, and not from Ombi/Radarr/Sonarr')
    submit = SubmitField('Save')

app/settings/__init__.py
from flask import Blueprint

bp = Blueprint('settings', __name__)

from app.settings import routes

app/settings/routes.py
from flask import render_template, flash, redirect, request, url_for, current_app
from app import db
from app.decorators import admin_required, super_user_required
from app.settings import bp
from app.models import User, AppSettings, Media, Pick, Movie, TVShow
from app.settings.forms import EditUserForm, AddUserForm, EditAppSettings
from flask_login import login_required

@bp.route('/application', methods=['GET', 'POST'])
@login_required
@admin_required
def application():
    num_picks = Pick.query.count()
    num_movies = Movie.query.count()
    num_shows = TVShow.query.count()
    app_settings = AppSettings.query.first()
    form = EditAppSettings()
    if form.validate_on_submit():
        deletion_settings_changed = (
            app_settings.expiry_time_number != form.expiry_time_number.data or
            app_settings.expiry_time_unit != form.expiry_time_unit.data or
            app_settings.next_delete != form.next_delete.data or
            app_settings.deletion_time_number != form.deletion_time_number.data or
            app_settings.deletion_time_unit != form.deletion_time_unit.data
        )
        app_settings.expiry_time_number = form.expiry_time_number.data
        app_settings.expiry_time_unit = form.expiry_time_unit.data
        app_settings.next_delete = form.next_delete.data
        app_settings.deletion_time_number = form.deletion_time_number.data
        app_settings.deletion_time_unit = form.deletion_time_unit.data
        app_settings.app_name = form.app_name.data
        app_settings.radarr_host = form.radarr_host.data
        app_settings.radarr_port = form.radarr_port.data
        app_settings.radarr_api_key = form.radarr_api_key.data
        app_settings.sonarr_host = form.sonarr_host.data
        app_settings.sonarr_port = form.sonarr_port.data
        app_settings.sonarr_api_key = form.sonarr_api_key.data
        app_settings.ombi_host = form.ombi_host.data
        app_settings.ombi_port = form.ombi_port.data
        app_settings.ombi_api_key = form.ombi_api_key.data
        app_settings.safe_mode = form.safe_mode.data
        db.session.commit()
        if deletion_settings_changed:
            current_app.logger.info("Deletion settings have been changed. Updating deletion date of abandoned medias.")
            Media.update_all_deletion_details()
        flash('Your changes have been saved.', "success")
        return redirect(url_for('settings.application'))
    elif request.method == 'GET':
        form.expiry_time_number.data = app_settings.expiry_time_number
        form.expiry_time_unit.data = app_settings.expiry_time_unit
        form.next_delete.data = app_settings.next_delete
        form.deletion_time_number.data = app_settings.deletion_time_number
        form.deletion_time_unit.data = app_settings.deletion_time_unit
        form.app_name.data = app_settings.app_name
        form.radarr_host.data = app_settings.radarr_host
        form.radarr_port.data = app_settings.radarr_port
        form.radarr_api_key.data = app_settings.radarr_api_key
        form.sonarr_host.data = app_settings.sonarr_host
        form.sonarr_port.data = app_settings.sonarr_port
        form.sonarr_api_key.data = app_settings.sonarr_api_key
        form.ombi_host.data = app_settings.ombi_host
        form.ombi_port.data = app_settings.ombi_port
        form.ombi_api_key.data = app_settings.ombi_api_key
        form.safe_mode.data = app_settings.safe_mode
    else :
        flash('Error saving settings. Check error messages', "error")
    return render_template('settings/application.html', form=form, num_picks=num_picks, num_movies=num_movies, num_shows=num_shows)

@bp.route('/users')
@login_required
@super_user_required
def users():
    users = User.query.all()
    return render_template('settings/users.html', users=users)

@bp.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def user(user_id):
    user = User.query.get_or_404(user_id)
    form = EditUserForm()
    if form.validate_on_submit():
        #If this user is the last admin and admin is removed, we deny it.
        if (user.is_administrator() and (User.admins_count() <= 1)) and (form.role.data != "Administrator"):
            flash('Cannot disable the last administrator', "error")
        elif (user.is_system_user()):
            flash('Cannot change a system user', "error")
        else:
            user.set_role(form.role.data)
            user.set_alias(form.alias.data)
            flash('Your changes have been saved.', "success")
        return redirect(url_for('settings.users'))
    elif request.method == 'GET':
        form.email.data = user.email
        form.alias.data = user.alias
        form.role.data = user.role.name
        return render_template('settings/user.html', form=form)

@bp.route('/add_user', methods=['GET', 'POST'])
@login_required
@admin_required
def add_user():
    form = AddUserForm()
    if form.validate_on_submit():
        user = User(email=form.email.data, alias=form.alias.data)
        db.session.add(user)
        db.session.commit()
        user.set_role(form.role.data)
        flash('User has been added.', "success")
        return redirect(url_for('settings.users'))
    return render_template('settings/add_user.html', form=form)

@bp.route('/logs')
@login_required
@admin_required
def logs():
    return render_template('settings/logs.html')

app/templates/settings/add_user.html
{% extends 'base.html' %}
{% set active_page = "settings" %}

{% block content %}
    <span class="title"><h1>{% block title %} Add User {% endblock %}</h1></span>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}<br>
            {% for error in form.email.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.alias.label }}<br>
            {{ form.alias(size=32)  }}<br>
            {% for error in form.alias.errors %}
                <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.role.label }}<br>
            {{ form.role }}<br>
        </p>
        <p>
        <p>{{ form.submit() }}</p>
        </p>
    </form>
{% endblock %}

app/templates/settings/application.html
{% extends 'base.html' %}
{% set active_page = "settings" %}

{% block content %}
    <span class="title"><h1>{% block title %} Application Settings {% endblock %}</h1></span>
    <form action="" method="post">
        <div class="container">
            {{ form.hidden_tag() }}

            <div class="row row-cols-auto">
                <div class="column">
                    {{ form.app_name.label }}<br>
                    {{ form.app_name(size=32) }}
                </div>
                <div class="column">
                    {{ form.safe_mode }}{{ form.safe_mode.label }}
                </div>
            </div>
            <hr>
            <h1>Media Management</h1>
            There are {{ num_picks }} picks, {{ num_movies }} movies and {{ num_shows }} TV shows.<br>

            <div class="row row-cols-auto">
                <div class="column">
                    <h2>Expiry</h2>
                    {{ form.expiry_time_number.label }}<br>
                    {{ form.expiry_time_number }}  {{ form.expiry_time_unit }}<br>
                    {% for error in form.expiry_time_number.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
                <div class="column">
                    <h2>Deletion</h2>
                    {{ form.next_delete.label }}<br>
                    {{ form.next_delete(type="hidden") }}
                    <input class="form-control" name="next_delete_local" required type="datetime-local" id="next_delete_local">
                    <br>
                    {% for error in form.next_delete.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                    <br>
                    {{ form.deletion_time_number.label }} {{ form.deletion_time_number }} {{ form.deletion_time_unit }}<br>
                    {% for error in form.deletion_time_number.errors %}
                        <span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </div>
            </div>
            <hr>
            <h2>Connections</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Service</th>
                        <th scope="col">Hostname</th>
                        <th scope="col">Port</th>
                        <th scope="col">API Key</th>
                        <th scope="col"> </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th scope="row">Radarr</th>
                        <td> {{ form.radarr_host }} </td>
                        <td> {{ form.radarr_port }} </td>
                        <td> {{ form.radarr_api_key(size=35) }} </td>
                        <td><a onclick="testRadarr()" class="btn btn-info">Test</a></td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <th scope="row">Sonarr</th>
                        <td> {{ form.sonarr_host }} </td>
                        <td> {{ form.sonarr_port }} </td>
                        <td> {{ form.sonarr_api_key(size=35) }} </td>
                        <td><a onclick="testSonarr()" class="btn btn-info">Test</a></td>
                    </tr>
                </tbody>
                <tbody>
                    <tr>
                        <th scope="row">Ombi</th>
                        <td> {{ form.ombi_host }} </td>
                        <td> {{ form.ombi_port }} </td>
                        <td> {{ form.ombi_api_key(size=35) }} </td>
                        <td><a onclick="testOmbi()" class="btn btn-info">Test</a></td>
                    </tr>
                </tbody>
            </table>
            <p>{{ form.submit() }}</p>
        </div>
    </form>
    <br><hr>
    <h2>Jobs</h2>
    <a onclick="update_medias_and_requests()" class="btn btn-success">Trigger Update Job</a>
    <a onclick="delete_expired_medias()" class="btn btn-danger">Trigger Expired Media Deletion</a>
    <script>
        document.querySelector('#next_delete_local').addEventListener("change", (event) => {
            var datetimeLocal = document.querySelector('#next_delete_local').value;
            var datetimeUTC = moment.utc(new Date(datetimeLocal)).format('YYYY-MM-DDTHH:mm');
            document.querySelector('#next_delete').value = datetimeUTC;
        });

        $(document).ready(function () {
            var datetimeUTC = document.querySelector('#next_delete').value+"Z";
            var datetimeLocal = moment(datetimeUTC).format('YYYY-MM-DD HH:mm');
            document.querySelector('#next_delete_local').value = datetimeLocal;
        });

        async function testRadarr() {
            spinner.removeAttribute('hidden');
            params ={
                'host': document.getElementById('radarr_host').value,
                'port': parseInt(document.getElementById('radarr_port').value),
                'api_key': document.getElementById('radarr_api_key').value
            }
            fetch(BASE_URL+"api/settings/test_radarr_from_server", {
                headers: {
                    'Content-Type': 'application/json'
                },
                method : 'POST',
                body: JSON.stringify(params)
            })
            .then(function (response){
                spinner.setAttribute('hidden', '');
                if (response.ok) {
                    response.json()
                    .then(function(response) {
                        toastr.success(response.message)
                    })
                } else {
                    response.json()
                    .then(function(response) {
                        toastr.error(response.error)
                    })
                }
            })
            .catch(function(error) {
                console.log(error)
            })
        }

        async function testSonarr() {
            spinner.removeAttribute('hidden');
            params ={
                'host': document.getElementById('sonarr_host').value,
                'port': parseInt(document.getElementById('sonarr_port').value),
                'api_key': document.getElementById('sonarr_api_key').value
            }
            fetch(BASE_URL+"api/settings/test_sonarr_from_server", {
                headers: {
                    'Content-Type': 'application/json'
                },
                method : 'POST',
                body: JSON.stringify(params)
            })
            .then(function (response){
                spinner.setAttribute('hidden', '');
                if (response.ok) {
                    response.json()
                    .then(function(response) {
                        toastr.success(response.message)
                    })
                } else {
                    response.json()
                    .then(function(response) {
                        toastr.error(response.error)
                    })
                }
            })
            .catch(function(error) {
                console.log(error)
            })
        }

        async function testOmbi() {
            spinner.removeAttribute('hidden');
            params ={
                'host': document.getElementById('ombi_host').value,
                'port': parseInt(document.getElementById('ombi_port').value),
                'api_key': document.getElementById('ombi_api_key').value
            }
            fetch(BASE_URL+"api/settings/test_ombi_from_server", {
                headers: {
                    'Content-Type': 'application/json'
                },
                method : 'POST',
                body: JSON.stringify(params)
            })
            .then(function (response){
                spinner.setAttribute('hidden', '');
                if (response.ok) {
                    response.json()
                    .then(function(response) {
                        toastr.success(response.message)
                    })
                } else {
                    response.json()
                    .then(function(response) {
                        toastr.error(response.error)
                    })
                }
            })
            .catch(function(error) {
                console.log(error)
            })
        }

        function update_medias_and_requests() {
            spinner.removeAttribute('hidden');
            fetch(BASE_URL+"api/jobs/trigger_update_medias_and_requests_job", {
                headers: {
                    'Content-Type': 'application/json'
                },
                method : 'POST',
            })
            .then(function (response){
                spinner.setAttribute('hidden', '');
                if (response.ok) {
                    response.json()
                    .then(function(response) {
                        toastr.success(response.message)
                    })
                } else {
                    response.json()
                    .then(function(response) {
                        toastr.error(response.error)
                    })
                }
            })
            .catch(function(error) {
                console.log(error)
            })
        }

        function delete_expired_medias() {
            var result = confirm("Are you sure you want to delete expired medias")
            if (result) {
                spinner.removeAttribute('hidden');
                fetch(BASE_URL+"api/jobs/trigger_delete_expired_medias_job", {
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    method : 'POST',
                })
                .then(function (response){
                    spinner.setAttribute('hidden', '');
                    if (response.ok) {
                        response.json()
                        .then(function(response) {
                            toastr.success(response.message)
                        })
                    } else {
                        response.json()
                        .then(function(response) {
                            toastr.error(response.error)
                        })
                    }
                })
                .catch(function(error) {
                    console.log(error)
                })
            }
        }
    </script>
{% endblock %}

app/templates/settings/logs.html
{% extends 'base.html' %}
{% set active_page = "settings" %}

{% block content %}
    <span hidden class="title">{% block title %} Live logs {% endblock %}</span>
    <div class='wrapper text-center'>
        <input type="radio" class="btn-check" name="options-base" id="option1" autocomplete="off">
        <label class="btn" for="option1" onclick="openLog(event, 'app')" style="background-color: rgb(65, 65, 65);">Application Log</label>

        <input type="radio" class="btn-check" name="options-base" id="option2" autocomplete="off">
        <label class="btn" for="option2" onclick="openLog(event, 'www')" style="background-color: rgb(65, 65, 65);">Web Log</label>
    </div>
    <br>
    <div class="logging_window">
        <div class="logging_content">
            <pre class="log_text" id="output"></pre>
        </div>
    </div>

    <script>
        //This is to avoid lingering requests if the user selects multiple tabs on one visit.
        var loopID = 0;
        var xhr = new XMLHttpRequest();
        function openLog(evt, logName) {
            clearInterval(loopID)
            xhr.abort();
            if (logName=="app") {
                var fetch_url = "{{ url_for('api.stream_applog') }}"
            } else if (logName=="www") {
                var fetch_url = "{{ url_for('api.stream_wwwlog') }}"
            }

            var output = document.getElementById('output');
            
            xhr.open('GET', fetch_url);
            xhr.send();
            loopID = setInterval(function() {
                output.textContent = xhr.responseText;
            }, 1000);
        }
    </script>
{% endblock %}

app/templates/settings/user.html
{% extends 'base.html' %}
{% set active_page = "settings" %}

{% block content %}
    <span class="title"><h1>{% block title %} Edit User {% endblock %}</h1></span>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32, disabled=True) }}<br>
        </p>
        <p>
            {{ form.alias.label }}<br>
            {{ form.alias(size=32)  }}<br>
            {% for error in form.alias.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
        </p>
        <p>
            {{ form.role.label }}<br>
            {{ form.role }}<br>
        </p>
        <p>
        <p>{{ form.submit() }}</p>
        </p>
    </form>
{% endblock %}

app/templates/settings/users.html
{% extends 'base.html' %}
{% set active_page = "settings" %}

{% block content %}
    <span class="title"><h1>{% block title %} Users {% endblock %}</h1></span>
    <hr>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Email</th>
                <th scope="col">Alias</th>
                <th scope="col">Movie Storage</th>
                <th scope="col">TV Show Storage</th>
                <th scope="col">Role</th>
                <th scope="col">Last Seen</th>
                {% if current_user.is_administrator() %}
                    <th scope="col">Edit</th>
                    <th scope="col">Delete</th>
                {% endif %}
            </tr>
        </thead>
        {% for user in users %}
            <tbody>
                <tr>
                    <th scope="row">{{user.email}}</th>
                    <td>{{user.alias}}</td>
                    <td><a href="{{ url_for('media.user_picks', user_id=user.id, media_type='movies') }}">{{user.movie_storage_usage | filesizeformat}}</a></td>
                    <td><a href="{{ url_for('media.user_picks', user_id=user.id, media_type='tv_shows') }}">{{user.show_storage_usage | filesizeformat}}</a></td>
                    <td>{{user.role.name}}</td>
                    {% if user.last_seen %}
                        <td>{{ moment(user.last_seen).format('LLL') }}</td>
                    {% else %}
                        <td>Never</td>
                    {% endif %}
                    {% if current_user.is_administrator() %}
                        {% if user.is_system_user() %}
                            <td><a class="btn btn-outline-light disabled" type="button" href="{{ url_for('settings.user', user_id=user.id) }}">Edit</a></td>
                            <td><a onclick="deleteUser({{user.id}}, this)" class="btn btn-danger disabled">Delete</a></td>
                        {% else %}
                            <td><a class="btn btn-outline-light" type="button" href="{{ url_for('settings.user', user_id=user.id) }}">Edit</a></td>
                            <td><a onclick="deleteUser({{user.id}}, this)" class="btn btn-danger">Delete</a></td>
                        {% endif %}
                    {% endif %}
                </tr>
            </tbody>
        {% endfor %}
    </table>
    <a class="btn btn-outline-light" type="button" href="{{ url_for('settings.add_user') }}">Add a user</a>

    <script>
        function deleteUser(user_id, obj) {
            var fetchURL = BASE_URL+"api/users/"+user_id+"/delete"
            var result = confirm("Are you sure you want to delete this user : "+obj.parentNode.parentNode.firstChild.nextElementSibling.innerText)
            if (result) {
                fetchToastRemoveRowTable(fetchURL, obj, 'DELETE')
            }
        }
    </script>
{% endblock %}